version: "3.8"

services:
  vinyl-web:
    build: .
    container_name: vinyl-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"  
    networks:
      - default
      - jellyfin_default  

  vinyl-bot:
    build: .
    container_name: vinyl-bot
    restart: unless-stopped
    env_file:
      - .env
    command: python -m vinyl_recorder.telegram_bot
    depends_on:
      - vinyl-web


networks:
  default:
  jellyfin_default:
    external: true
